import { notFound } from "next/navigation";
import { ArrowLeft, Building2, Globe2, Mail, Phone } from "lucide-react";
import Link from "next/link";
import { db } from "@/lib/db";
import { InquiryActions } from "@/components/admin/inquiry-actions";
import { Status } from "@/app/admin/(crm)/page";
import { getAdminLocale, pick } from "@/lib/admin-i18n";

export const dynamic = "force-dynamic";

export default async function InquiryDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const locale = await getAdminLocale(); const inquiry = await db.inquiry.findUnique({ where: { id }, include: { customer: true, items: { include: { product: true } }, emails: { orderBy: { createdAt: "desc" } }, notes: { orderBy: { createdAt: "desc" } } } }); if (!inquiry) notFound(); const product = inquiry.items[0]?.product;
  return <main className="p-5 sm:p-8 lg:p-10"><div className="mx-auto max-w-[1200px]"><Link href="/admin/inquiries" className="mb-6 flex items-center gap-2 text-xs font-bold text-[#6e7a74]"><ArrowLeft size={15} />{pick(locale, "All inquiries", "全部询盘")}</Link><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-3"><h1 className="display text-4xl">{inquiry.inquiryNo}</h1><Status value={inquiry.status} locale={locale} /></div><p className="mt-2 text-sm text-[#748079]">{pick(locale, "Received", "收到时间")} {inquiry.createdAt.toLocaleString(locale === "zh" ? "zh-CN" : "en-US")}</p></div><InquiryActions id={inquiry.id} status={inquiry.status} assignedTo={inquiry.assignedTo} nextFollowUp={inquiry.nextFollowUp?.toISOString() || null} locale={locale} /></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="space-y-5"><section className="surface p-6"><p className="text-xs font-black uppercase text-[#0b5d43]">{pick(locale, "Buying requirement", "采购需求")}</p><h2 className="display mt-2 text-2xl">{locale === "zh" ? product?.nameZh : product?.nameEn || inquiry.subject}</h2><p className="mt-5 whitespace-pre-wrap text-sm leading-7 text-[#4e5c55]">{inquiry.message}</p><div className="mt-6 grid gap-px overflow-hidden rounded-[6px] bg-[#dfe6e2] sm:grid-cols-4">{[[pick(locale, "Quantity", "数量"), inquiry.quantity?.toLocaleString() || "-"], [pick(locale, "Target price", "目标价"), inquiry.targetPrice ? `$${inquiry.targetPrice}` : "-"], [pick(locale, "Incoterm", "贸易术语"), inquiry.incoterm || "-"], [pick(locale, "Destination", "目的地"), inquiry.destination || "-"]].map(([a,b]) => <div key={a} className="bg-[#f7f9f7] p-4"><span className="text-[10px] font-bold text-[#849089]">{a}</span><b className="mt-1 block text-sm">{b}</b></div>)}</div></section><section className="surface p-6"><h2 className="font-bold">{pick(locale, "Internal notes", "内部备注")}</h2><div className="mt-5 space-y-3">{inquiry.notes.map((n) => <div key={n.id} className="rounded-[6px] bg-[#f4f7f5] p-4"><p className="text-sm leading-6">{n.content}</p><span className="mt-2 block text-[10px] text-[#859089]">{n.author} · {n.createdAt.toLocaleString(locale === "zh" ? "zh-CN" : "en-US")}</span></div>)}{!inquiry.notes.length && <p className="text-sm text-[#859089]">{pick(locale, "No notes yet. Use the action panel to add context.", "暂无备注，可使用更新面板添加销售背景。")}</p>}</div></section></div>
      <aside className="space-y-5"><section className="surface p-5"><h2 className="font-bold">{pick(locale, "Buyer profile", "买家资料")}</h2><div className="mt-5 flex items-center gap-3"><div className="grid size-11 place-items-center rounded-[6px] bg-[#e7f1ec] font-bold text-[#0b5d43]">{inquiry.customer.name.slice(0,2).toUpperCase()}</div><div><b className="text-sm">{inquiry.customer.name}</b><p className="text-xs text-[#7b8781]">{inquiry.customer.company || pick(locale, "Independent buyer", "独立买家")}</p></div></div><div className="mt-5 space-y-3 text-xs text-[#53615a]"><Info icon={Mail}>{inquiry.customer.email}</Info><Info icon={Phone}>{inquiry.customer.phone || pick(locale, "No phone", "无电话")}</Info><Info icon={Globe2}>{inquiry.customer.country || pick(locale, "Unknown country", "未知国家")}</Info><Info icon={Building2}>{inquiry.customer.company || pick(locale, "No company", "无公司")}</Info></div></section><section className="surface p-5"><h2 className="font-bold">{pick(locale, "Email activity", "邮件记录")}</h2><div className="mt-4 space-y-3">{inquiry.emails.map((e) => <div key={e.id} className="border-l-2 border-[#dce5e0] pl-3"><div className="flex justify-between gap-2 text-xs"><b>{e.type === "CUSTOMER_CONFIRMATION" ? pick(locale, "Buyer confirmation", "客户确认邮件") : pick(locale, "Sales notification", "销售通知邮件")}</b><span className={e.status === "SENT" ? "text-emerald-700" : "text-amber-700"}>{e.status}</span></div><p className="mt-1 truncate text-[10px] text-[#849089]">{e.recipient}</p>{e.error && <p className="mt-1 text-[10px] text-red-600">{e.error}</p>}</div>)}</div></section></aside></div></div></main>;
}
function Info({ icon: Icon, children }: { icon: React.ComponentType<{ size?: number; className?: string }>; children: React.ReactNode }) { return <div className="flex items-center gap-2.5"><Icon size={14} className="text-[#0b5d43]" /><span className="truncate">{children}</span></div>; }
