import Link from "next/link";
import { ArrowUpRight, Clock3, Inbox, MailCheck, Users } from "lucide-react";
import { db } from "@/lib/db";
import { getAdminLocale, pick, statusText, type AdminLocale } from "@/lib/admin-i18n";

export const dynamic = "force-dynamic";

export default async function Dashboard() {
  const locale = await getAdminLocale();
  const [inquiries, customers, newCount, emailSent] = await Promise.all([
    db.inquiry.findMany({ include: { customer: true, items: { include: { product: true } } }, orderBy: { createdAt: "desc" }, take: 6 }),
    db.customer.count(), db.inquiry.count({ where: { status: "NEW" } }), db.emailLog.count({ where: { status: "SENT" } }),
  ]);
  const total = await db.inquiry.count();
  return <main className="p-5 sm:p-8 lg:p-10"><div className="mx-auto max-w-[1300px]"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase text-[#0b5d43]">{pick(locale, "Sales command center", "销售指挥中心")}</p><h1 className="display mt-2 text-4xl">{pick(locale, "Good morning.", "早上好。")}</h1><p className="mt-2 text-sm text-[#6c7872]">{pick(locale, "Here is what needs attention across your pipeline.", "以下是销售管道中需要关注的事项。")}</p></div><div className="text-xs text-[#7a867f]">{pick(locale, "Updated", "更新于")} {new Date().toLocaleDateString(locale === "zh" ? "zh-CN" : "en-US", { month: "long", day: "numeric", year: "numeric" })}</div></div>
    <section className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Inbox} label={pick(locale, "Total inquiries", "询盘总数")} value={total} detail={pick(locale, `${newCount} awaiting review`, `${newCount} 个待审核`)} /><Metric icon={Users} label={pick(locale, "Active customers", "活跃客户")} value={customers} detail={pick(locale, "Unique buyer accounts", "独立买家账户")} /><Metric icon={Clock3} label={pick(locale, "New pipeline", "新询盘管道")} value={newCount} detail={pick(locale, "Requires first response", "需要首次回复")} accent /><Metric icon={MailCheck} label={pick(locale, "Emails delivered", "已发送邮件")} value={emailSent} detail={pick(locale, "Provider-confirmed sends", "服务商确认发送")} /></section>
    <section className="mt-8 grid gap-5 xl:grid-cols-[1.45fr_.55fr]"><div className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-[#e2e8e4] p-5"><div><h2 className="font-bold">{pick(locale, "Latest inquiries", "最新询盘")}</h2><p className="mt-1 text-xs text-[#7c8882]">{pick(locale, "Newest buying signals across all markets", "来自各市场的最新采购信号")}</p></div><Link href="/admin/inquiries" className="text-xs font-bold text-[#0b5d43]">{pick(locale, "View all", "查看全部")}</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-[#f8faf8] text-[#7c8882]"><tr><th className="px-5 py-3">{pick(locale, "Buyer", "买家")}</th><th className="px-5 py-3">{pick(locale, "Product", "产品")}</th><th className="px-5 py-3">{pick(locale, "Quantity", "数量")}</th><th className="px-5 py-3">{pick(locale, "Status", "状态")}</th><th className="px-5 py-3">{pick(locale, "Received", "收到时间")}</th><th /></tr></thead><tbody>{inquiries.map((q) => <tr key={q.id} className="border-t border-[#e9eeeb]"><td className="px-5 py-4"><b className="block text-[#26342d]">{q.customer.name}</b><span className="text-[#85908a]">{q.customer.company || q.customer.country}</span></td><td className="px-5 py-4">{locale === "zh" ? q.items[0]?.product.nameZh : q.items[0]?.product.nameEn}</td><td className="px-5 py-4">{q.quantity?.toLocaleString() || "-"}</td><td className="px-5 py-4"><Status value={q.status} locale={locale} /></td><td className="px-5 py-4 text-[#78847e]">{relative(q.createdAt, locale)}</td><td className="px-5 py-4"><Link aria-label={`${pick(locale, "Open", "打开")} ${q.inquiryNo}`} href={`/admin/inquiries/${q.id}`}><ArrowUpRight size={16} /></Link></td></tr>)}</tbody></table>{!inquiries.length && <div className="p-10 text-center text-sm text-[#7c8882]">{pick(locale, "No inquiries yet. Submit one from the public website to see the workflow.", "暂无询盘。可从公开网站提交一条询盘体验流程。")}</div>}</div></div>
      <div className="surface p-5"><h2 className="font-bold">{pick(locale, "Pipeline health", "系统运行状态")}</h2><p className="mt-1 text-xs text-[#7c8882]">{pick(locale, "Operational checklist", "运行配置检查")}</p><div className="mt-7 space-y-5"><Health label={pick(locale, "DeepSeek knowledge base", "DeepSeek 产品知识库")} ok={Boolean(process.env.DEEPSEEK_API_KEY)} locale={locale} /><Health label={pick(locale, "Email delivery", "邮件发送")} ok={Boolean(process.env.RESEND_API_KEY)} locale={locale} /><Health label={pick(locale, "Database", "数据库")} ok locale={locale} /><Health label={pick(locale, "Authentication", "身份验证")} ok={Boolean(process.env.AUTH_SECRET)} locale={locale} /></div><Link href="/admin/settings" className="mt-8 flex items-center justify-between rounded-[6px] bg-[#edf4f0] p-4 text-xs font-bold text-[#0b5d43]">{pick(locale, "Review configuration", "查看配置")} <ArrowUpRight size={15} /></Link></div></section>
  </div></main>;
}

function Metric({ icon: Icon, label, value, detail, accent }: { icon: React.ComponentType<{ size?: number }>; label: string; value: number; detail: string; accent?: boolean }) { return <div className={`rounded-[8px] border p-5 ${accent ? "border-[#0b5d43] bg-[#0b5d43] text-white" : "border-[#dde5e0] bg-white"}`}><div className="flex items-center justify-between"><span className={`text-xs font-bold ${accent ? "text-white/65" : "text-[#76827c]"}`}>{label}</span><Icon size={17} /></div><div className="display mt-5 text-4xl">{value}</div><p className={`mt-2 text-[11px] ${accent ? "text-white/60" : "text-[#8a958f]"}`}>{detail}</p></div>; }
function Health({ label, ok = false, locale }: { label: string; ok?: boolean; locale: AdminLocale }) { return <div className="flex items-center justify-between text-xs"><span className="text-[#53615a]">{label}</span><span className={`rounded-full px-2 py-1 font-bold ${ok ? "bg-[#e7f2ec] text-[#0b5d43]" : "bg-amber-50 text-amber-700"}`}>{ok ? pick(locale, "Ready", "已就绪") : pick(locale, "Configure", "待配置")}</span></div>; }
export function Status({ value, locale = "en" }: { value: string; locale?: AdminLocale }) { const styles: Record<string,string> = { NEW: "bg-[#fff0e9] text-[#b95235]", CONTACTED: "bg-blue-50 text-blue-700", QUALIFIED: "bg-violet-50 text-violet-700", QUOTED: "bg-amber-50 text-amber-700", WON: "bg-emerald-50 text-emerald-700", LOST: "bg-gray-100 text-gray-600" }; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${styles[value] || styles.NEW}`}>{statusText[locale][value] || value}</span>; }
function relative(date: Date, locale: AdminLocale) { const hours = Math.floor((Date.now() - date.getTime()) / 3600000); return hours < 1 ? pick(locale, "Just now", "刚刚") : hours < 24 ? pick(locale, `${hours}h ago`, `${hours} 小时前`) : pick(locale, `${Math.floor(hours / 24)}d ago`, `${Math.floor(hours / 24)} 天前`); }
