"use client";

import * as Dialog from "@radix-ui/react-dialog";
import { Loader2, PencilLine, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input, Textarea } from "@/components/ui/input";
import type { AdminLocale } from "@/lib/admin-i18n";

export function InquiryActions({ id, status, assignedTo, nextFollowUp, locale }: { id: string; status: string; assignedTo: string | null; nextFollowUp: string | null; locale: AdminLocale }) {
  const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  async function submit(formData: FormData) { setLoading(true); setError(""); const next = String(formData.get("nextFollowUp") || ""); const payload = { status: formData.get("status"), assignedTo: String(formData.get("assignedTo") || "") || null, nextFollowUp: next ? new Date(next).toISOString() : null, note: String(formData.get("note") || "") || undefined }; const response = await fetch(`/api/admin/inquiries/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) { setError((await response.json()).error); setLoading(false); return; } setOpen(false); setLoading(false); router.refresh(); }
  const zh = locale === "zh";
  return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><Button><PencilLine size={16} />{zh ? "更新询盘" : "Update inquiry"}</Button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-[#071b14]/60" /><Dialog.Content className="fixed left-1/2 top-1/2 z-50 w-[min(500px,calc(100%-24px))] -translate-x-1/2 -translate-y-1/2 rounded-[8px] bg-white p-6 shadow-2xl"><Dialog.Title className="display text-2xl">{zh ? "更新询盘" : "Update inquiry"}</Dialog.Title><Dialog.Description className="mt-1 text-xs text-[#7b8781]">{zh ? "推进销售进度并记录下一步行动。" : "Move the deal forward and document the next action."}</Dialog.Description><Dialog.Close className="absolute right-4 top-4"><X size={18} /></Dialog.Close><form action={submit} className="mt-6 space-y-4"><label className="grid gap-1.5 text-xs font-bold">{zh ? "状态" : "Status"}<select name="status" defaultValue={status} className="h-11 rounded-[6px] border border-[#d6dfda] bg-white px-3 text-sm"><option>NEW</option><option>CONTACTED</option><option>QUALIFIED</option><option>QUOTED</option><option>WON</option><option>LOST</option></select></label><label className="grid gap-1.5 text-xs font-bold">{zh ? "负责人" : "Assigned to"}<Input name="assignedTo" defaultValue={assignedTo || ""} placeholder={zh ? "销售负责人" : "Sales owner"} /></label><label className="grid gap-1.5 text-xs font-bold">{zh ? "下次跟进" : "Next follow-up"}<Input name="nextFollowUp" type="datetime-local" defaultValue={nextFollowUp?.slice(0,16) || ""} /></label><label className="grid gap-1.5 text-xs font-bold">{zh ? "添加内部备注" : "Add internal note"}<Textarea name="note" placeholder={zh ? "通话结果、报价背景、客户异议..." : "Call outcome, quotation context, objections..."} /></label>{error && <p className="text-xs text-red-700">{error}</p>}<Button disabled={loading} className="w-full">{loading && <Loader2 className="animate-spin" size={16} />}{zh ? "保存更新" : "Save update"}</Button></form></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
