"use client";

import { ArrowLeft, ArrowRight, CheckCircle2, ClipboardCheck, Loader2, Sparkles } from "lucide-react";
import { useState } from "react";
import { SolutionHeader } from "@/components/solutions/solution-header";
import { Button } from "@/components/ui/button";
import { Input, Textarea } from "@/components/ui/input";

type Product = { id: string; nameEn: string; nameZh: string; moq: number };
type FormState = Record<string, string>;

const initial: FormState = { name: "", email: "", company: "", country: "", phone: "", productId: "", quantity: "", timeline: "", budgetStatus: "", decisionRole: "", targetPrice: "", destination: "", incoterm: "FOB", requirements: "", website: "" };

export function BuyerIntentExperience({ products, initialLanguage, isAdmin }: { products: Product[]; initialLanguage: "en" | "zh"; isAdmin: boolean }) {
  const [language, setLanguage] = useState(initialLanguage); const [step, setStep] = useState(0); const [form, setForm] = useState<FormState>({ ...initial, productId: products[0]?.id || "" }); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<{ inquiryNo: string; level: string; score: number; summary: string; emailQueued: boolean }>(); const zh = language === "zh";
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const valid = step === 0 ? Boolean(form.name.length > 1 && form.email.includes("@") && form.company.length > 1 && form.country.length > 1) : step === 1 ? Boolean(form.productId && Number(form.quantity) > 0 && form.timeline) : step === 2 ? Boolean(form.budgetStatus && form.decisionRole && form.destination.length > 1 && form.incoterm) : form.requirements.length >= 10;
  async function submit() { setLoading(true); setError(""); const response = await fetch("/api/buyer-intent", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, language }) }); const data = await response.json(); if (!response.ok) { setError(data.error || (zh ? "提交失败" : "Submission failed")); setLoading(false); return; } setResult(data); setLoading(false); }
  const labels = zh ? ["联系信息", "产品计划", "商务条件", "需求确认"] : ["Contact", "Product plan", "Commercial terms", "Review"];
  return <main className="min-h-screen bg-[#f5f8f6]"><SolutionHeader language={language} onLanguageChange={setLanguage} isAdmin={isAdmin} />
    <section className="bg-[#073c2c] py-14 text-white"><div className="shell"><span className="flex items-center gap-2 text-xs font-black uppercase text-[#d8f06d]"><ClipboardCheck size={15} />{zh ? "采购意向识别" : "Buyer qualification"}</span><h1 className="display mt-4 max-w-4xl text-5xl leading-tight sm:text-6xl">{zh ? "用四个步骤，把采购想法变成清晰询盘。" : "Turn buying intent into a clear RFQ in four focused steps."}</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-white/65">{zh ? "当前采用透明、低成本的规则评分。客户量增长后可以无缝升级为 DeepSeek 智能分析。" : "The current qualification uses transparent, low-cost rules and can later upgrade to DeepSeek analysis without changing the workflow."}</p></div></section>
    <div className="shell py-10 sm:py-14">{result ? <Result result={result} language={language} /> : <div className="grid gap-8 lg:grid-cols-[280px_1fr]"><aside><div className="space-y-1">{labels.map((label, index) => <div key={label} className={`flex items-center gap-3 rounded-[6px] px-3 py-3 text-sm ${index === step ? "bg-[#0b5d43] font-bold text-white" : index < step ? "text-[#0b5d43]" : "text-[#829089]"}`}><span className={`grid size-7 place-items-center rounded-full text-xs font-black ${index < step ? "bg-[#d8f06d]" : index === step ? "bg-white/15" : "bg-[#e5ebe8]"}`}>{index < step ? <CheckCircle2 size={15} /> : index + 1}</span>{label}</div>)}</div><div className="mt-6 rounded-[7px] border border-[#dce5e0] bg-white p-4 text-xs leading-6 text-[#64716b]"><Sparkles className="mb-2 text-[#0b5d43]" size={18} />{zh ? "完成后会自动生成询盘编号、采购摘要和基础意向等级，并同步至 CRM。" : "Completion creates an inquiry reference, buying summary and basic intent level, then syncs it to CRM."}</div></aside>
      <section className="rounded-[8px] border border-[#dce5e0] bg-white p-5 sm:p-8"><div className="mb-7"><p className="text-xs font-black text-[#f27c5a]">0{step + 1} / 04</p><h2 className="display mt-2 text-3xl">{labels[step]}</h2></div>
        {step === 0 && <div className="grid gap-4 sm:grid-cols-2"><Field label={zh ? "姓名 *" : "Full name *"}><Input value={form.name} onChange={(e) => update("name", e.target.value)} /></Field><Field label={zh ? "工作邮箱 *" : "Business email *"}><Input type="email" value={form.email} onChange={(e) => update("email", e.target.value)} /></Field><Field label={zh ? "公司 *" : "Company *"}><Input value={form.company} onChange={(e) => update("company", e.target.value)} /></Field><Field label={zh ? "国家/地区 *" : "Country / region *"}><Input value={form.country} onChange={(e) => update("country", e.target.value)} /></Field><Field label={zh ? "电话 / WhatsApp" : "Phone / WhatsApp"}><Input value={form.phone} onChange={(e) => update("phone", e.target.value)} /></Field><input className="hidden" value={form.website} onChange={(e) => update("website", e.target.value)} tabIndex={-1} /></div>}
        {step === 1 && <div className="grid gap-4 sm:grid-cols-2"><Field label={zh ? "采购产品 *" : "Product *"}><select value={form.productId} onChange={(e) => update("productId", e.target.value)} className="h-11 rounded-[6px] border border-[#d6dfda] bg-white px-3 text-sm">{products.map((product) => <option value={product.id} key={product.id}>{zh ? product.nameZh : product.nameEn} · MOQ {product.moq}</option>)}</select></Field><Field label={zh ? "预计数量 *" : "Estimated quantity *"}><Input type="number" min="1" value={form.quantity} onChange={(e) => update("quantity", e.target.value)} /></Field><Choice label={zh ? "计划采购时间 *" : "Purchase timeline *"} value={form.timeline} onChange={(value) => update("timeline", value)} options={zh ? [["within-30", "30 天内"], ["one-to-three", "1-3 个月"], ["three-to-six", "3-6 个月"], ["researching", "正在调研"]] : [["within-30", "Within 30 days"], ["one-to-three", "1-3 months"], ["three-to-six", "3-6 months"], ["researching", "Researching"]]} /></div>}
        {step === 2 && <div className="grid gap-5 sm:grid-cols-2"><Choice label={zh ? "预算状态 *" : "Budget status *"} value={form.budgetStatus} onChange={(value) => update("budgetStatus", value)} options={zh ? [["approved", "预算已批准"], ["estimated", "已有估算"], ["unknown", "尚未确定"]] : [["approved", "Approved"], ["estimated", "Estimated"], ["unknown", "Not decided"]]} /><Choice label={zh ? "您的采购角色 *" : "Your role *"} value={form.decisionRole} onChange={(value) => update("decisionRole", value)} options={zh ? [["decision-maker", "决策人"], ["influencer", "参与决策"], ["researcher", "资料调研"]] : [["decision-maker", "Decision maker"], ["influencer", "Influencer"], ["researcher", "Researcher"]]} /><Field label={zh ? "目标单价（美元）" : "Target price (USD)"}><Input type="number" min="0" step="0.01" value={form.targetPrice} onChange={(e) => update("targetPrice", e.target.value)} /></Field><Field label={zh ? "目的港 / 城市 *" : "Destination port / city *"}><Input value={form.destination} onChange={(e) => update("destination", e.target.value)} /></Field><Field label={zh ? "贸易术语 *" : "Incoterm *"}><select value={form.incoterm} onChange={(e) => update("incoterm", e.target.value)} className="h-11 rounded-[6px] border border-[#d6dfda] bg-white px-3 text-sm"><option>EXW</option><option>FOB</option><option>CIF</option><option>DDP</option><option>Not sure</option></select></Field></div>}
        {step === 3 && <div><Field label={zh ? "规格、认证、包装及其他要求 *" : "Specifications, certifications, packaging and other requirements *"}><Textarea className="min-h-44" value={form.requirements} onChange={(e) => update("requirements", e.target.value)} placeholder={zh ? "请尽量详细说明您的采购要求..." : "Describe your buying requirements in detail..."} /></Field><div className="mt-5 grid gap-3 rounded-[7px] bg-[#f1f5f3] p-4 text-xs sm:grid-cols-3"><Review label={zh ? "公司" : "Company"} value={form.company} /><Review label={zh ? "数量" : "Quantity"} value={Number(form.quantity).toLocaleString()} /><Review label={zh ? "目的地" : "Destination"} value={form.destination} /></div></div>}
        {error && <p className="mt-5 rounded-[6px] bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-8 flex items-center justify-between border-t border-[#e4eae6] pt-5"><Button variant="ghost" disabled={step === 0 || loading} onClick={() => setStep((current) => current - 1)}><ArrowLeft size={16} />{zh ? "上一步" : "Back"}</Button>{step < 3 ? <Button disabled={!valid} onClick={() => setStep((current) => current + 1)}>{zh ? "下一步" : "Continue"}<ArrowRight size={16} /></Button> : <Button disabled={!valid || loading} onClick={submit}>{loading ? <Loader2 className="animate-spin" size={16} /> : <ClipboardCheck size={16} />}{zh ? "生成并提交询盘" : "Create and submit RFQ"}</Button>}</div>
      </section></div>}</div>
  </main>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-xs font-bold text-[#46534d]">{label}{children}</label>; }
function Choice({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <fieldset className="sm:col-span-2"><legend className="mb-2 text-xs font-bold text-[#46534d]">{label}</legend><div className="grid gap-2 sm:grid-cols-2">{options.map(([key, text]) => <button type="button" key={key} onClick={() => onChange(key)} className={`rounded-[6px] border px-4 py-3 text-left text-sm transition ${value === key ? "border-[#0b5d43] bg-[#e8f1ed] font-bold text-[#0b5d43]" : "border-[#d8e1dc] hover:border-[#8caaa0]"}`}>{text}</button>)}</div></fieldset>; }
function Review({ label, value }: { label: string; value: string }) { return <div><span className="text-[#829089]">{label}</span><b className="mt-1 block text-[#26342d]">{value || "-"}</b></div>; }
function Result({ result, language }: { result: { inquiryNo: string; level: string; score: number; summary: string; emailQueued: boolean }; language: "en" | "zh" }) { const zh = language === "zh"; return <div className="mx-auto max-w-3xl rounded-[8px] border border-[#d9e3de] bg-white p-7 text-center shadow-[0_18px_50px_rgba(7,60,44,.08)] sm:p-10"><CheckCircle2 className="mx-auto text-[#0b5d43]" size={52} /><p className="mt-5 text-xs font-black uppercase text-[#f27c5a]">{zh ? "询盘已进入 CRM" : "RFQ synced to CRM"}</p><h2 className="display mt-2 text-4xl">{zh ? "采购需求已生成" : "Buying request created"}</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-[#64716b]">{result.summary}</p><div className="mx-auto mt-7 grid max-w-lg gap-px overflow-hidden rounded-[7px] bg-[#dce5e0] sm:grid-cols-3"><ReviewBox label={zh ? "询盘编号" : "Reference"} value={result.inquiryNo} /><ReviewBox label={zh ? "基础意向" : "Basic intent"} value={result.level} /><ReviewBox label={zh ? "规则得分" : "Rule score"} value={`${result.score}/100`} /></div><p className="mt-5 text-xs text-[#7a867f]">{result.emailQueued ? (zh ? "确认邮件已发送。" : "Confirmation email sent.") : (zh ? "邮件服务尚未配置，请保存询盘编号。" : "Email is not configured; save the inquiry reference.")}</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Button asChild><a href={`/solutions/follow-up?lang=${language}`}>{zh ? "查看跟进进度" : "Track follow-up"}</a></Button><Button asChild variant="outline"><a href={`/?lang=${language}`}>{zh ? "返回首页" : "Back to home"}</a></Button></div></div>; }
function ReviewBox({ label, value }: { label: string; value: string }) { return <div className="bg-[#f1f5f3] p-4"><span className="text-[10px] font-bold text-[#7b8781]">{label}</span><b className="mt-1 block break-all text-sm text-[#0b5d43]">{value}</b></div>; }
