"use client";

import { CalendarClock, CheckCircle2, Loader2, Search, UserRound } from "lucide-react";
import { useState } from "react";
import { SolutionHeader } from "@/components/solutions/solution-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Result = { inquiryNo: string; status: string; product?: string; assignedTo?: string | null; nextFollowUp?: string | null; updatedAt: string; events: Array<{ id: string; title: string; description: string; createdAt: string }> };

export function FollowUpExperience({ initialLanguage, isAdmin }: { initialLanguage: "en" | "zh"; isAdmin: boolean }) {
  const [language, setLanguage] = useState(initialLanguage); const [inquiryNo, setInquiryNo] = useState(""); const [email, setEmail] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<Result>(); const zh = language === "zh";
  async function lookup(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); setResult(undefined); const response = await fetch("/api/inquiry-status", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ inquiryNo, email, language }) }); const data = await response.json(); if (!response.ok) { setError(data.error); setLoading(false); return; } setResult(data); setLoading(false); }
  const status: Record<string, string> = zh ? { NEW: "待审核", CONTACTED: "已联系", QUALIFIED: "需求已确认", QUOTED: "已报价", WON: "已成交", LOST: "已结束" } : { NEW: "Awaiting review", CONTACTED: "Contacted", QUALIFIED: "Requirements confirmed", QUOTED: "Quotation sent", WON: "Order won", LOST: "Closed" };
  return <main className="min-h-screen bg-[#f5f8f6]"><SolutionHeader language={language} onLanguageChange={setLanguage} isAdmin={isAdmin} />
    <section className="bg-[#073c2c] py-14 text-white"><div className="shell grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><span className="flex items-center gap-2 text-xs font-black uppercase text-[#d8f06d]"><CalendarClock size={15} />{zh ? "销售及时跟进" : "Sales follow-up"}</span><h1 className="display mt-4 text-5xl leading-tight sm:text-6xl">{zh ? "随时掌握询盘进展，无需反复催问。" : "Know where your inquiry stands without chasing for updates."}</h1></div><p className="text-sm leading-7 text-white/65">{zh ? "使用询盘编号和提交时的邮箱进行验证，只显示可向客户公开的进度信息。" : "Verify with the inquiry reference and submission email. Only buyer-safe progress information is shown."}</p></div></section>
    <div className="shell grid gap-8 py-12 lg:grid-cols-[.72fr_1.28fr]"><section><form onSubmit={lookup} className="rounded-[8px] border border-[#dbe4df] bg-white p-6"><h2 className="font-bold">{zh ? "查询询盘" : "Find your inquiry"}</h2><p className="mt-2 text-xs leading-5 text-[#748079]">{zh ? "编号格式示例：TP-20260718-ABC123" : "Reference example: TP-20260718-ABC123"}</p><label className="mt-6 grid gap-2 text-xs font-bold">{zh ? "询盘编号" : "Inquiry reference"}<Input required value={inquiryNo} onChange={(e) => setInquiryNo(e.target.value.toUpperCase())} placeholder="TP-..." /></label><label className="mt-4 grid gap-2 text-xs font-bold">{zh ? "提交邮箱" : "Submission email"}<Input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="buyer@company.com" /></label>{error && <p className="mt-4 rounded-[6px] bg-red-50 p-3 text-xs leading-5 text-red-700">{error}</p>}<Button className="mt-5 w-full" disabled={loading}>{loading ? <Loader2 className="animate-spin" size={16} /> : <Search size={16} />}{zh ? "查询进度" : "Check progress"}</Button></form><div className="mt-4 rounded-[7px] bg-[#e9f1ed] p-4 text-xs leading-6 text-[#53615a]">{zh ? "为保护客户隐私，询盘编号和邮箱必须完全匹配。内部销售备注不会在此页面显示。" : "For privacy, the reference and email must match exactly. Internal sales notes are never displayed here."}</div></section>
      <section>{result ? <div className="rounded-[8px] border border-[#dbe4df] bg-white p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 border-b border-[#e2e8e4] pb-6 sm:flex-row"><div><p className="text-xs font-black uppercase text-[#0b5d43]">{result.inquiryNo}</p><h2 className="display mt-2 text-3xl">{result.product}</h2></div><span className="h-fit rounded-full bg-[#e6f1eb] px-4 py-2 text-xs font-black text-[#0b5d43]">{status[result.status] || result.status}</span></div><div className="grid gap-px overflow-hidden rounded-[7px] bg-[#dfe6e2] sm:grid-cols-2"><Info icon={UserRound} label={zh ? "负责人" : "Sales owner"} value={result.assignedTo || (zh ? "正在分配" : "Being assigned")} /><Info icon={CalendarClock} label={zh ? "下次跟进" : "Next follow-up"} value={result.nextFollowUp ? new Date(result.nextFollowUp).toLocaleString(zh ? "zh-CN" : "en-US") : (zh ? "销售确认后更新" : "Updated after sales review")} /></div><h3 className="mt-8 font-bold">{zh ? "进度记录" : "Progress timeline"}</h3><div className="mt-5 space-y-0">{result.events.map((item, index) => <div key={item.id} className="relative flex gap-4 pb-7"><div className="relative z-10 grid size-8 shrink-0 place-items-center rounded-full bg-[#0b5d43] text-white"><CheckCircle2 size={15} /></div>{index < result.events.length - 1 && <div className="absolute left-[15px] top-8 h-[calc(100%-32px)] w-px bg-[#d9e2dd]" />}<div><h4 className="text-sm font-bold">{item.title}</h4><p className="mt-1 text-xs leading-5 text-[#68756f]">{item.description}</p><time className="mt-2 block text-[10px] text-[#8a958f]">{new Date(item.createdAt).toLocaleString(zh ? "zh-CN" : "en-US")}</time></div></div>)}</div></div> : <div className="grid min-h-[480px] place-items-center rounded-[8px] border border-dashed border-[#bfcec7] bg-[#edf3f0] p-8 text-center"><div><Search className="mx-auto text-[#0b5d43]" size={36} /><h2 className="display mt-5 text-3xl">{zh ? "查询您的询盘进度" : "Track your inquiry progress"}</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-[#68756f]">{zh ? "输入左侧信息后，这里将显示当前状态、负责人、跟进时间和公开进度。" : "Enter the details to see current status, owner, next follow-up and public progress."}</p></div></div>}</section></div>
  </main>;
}

function Info({ icon: Icon, label, value }: { icon: React.ComponentType<{ size?: number; className?: string }>; label: string; value: string }) { return <div className="flex gap-3 bg-[#f4f7f5] p-4"><Icon className="text-[#0b5d43]" size={18} /><div><span className="text-[10px] font-bold text-[#7f8b85]">{label}</span><b className="mt-1 block text-sm">{value}</b></div></div>; }
