"use client";

import { ChevronDown, MessageCircleQuestion, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { SolutionHeader } from "@/components/solutions/solution-header";
import { InlineAiChat } from "@/components/solutions/inline-ai-chat";
import { Button } from "@/components/ui/button";

type Product = { id: string; nameEn: string; nameZh: string; description: string; moq: number; leadTime: string; specs: Record<string, string> };

export function ProductQaExperience({ products, initialLanguage, isAdmin }: { products: Product[]; initialLanguage: "en" | "zh"; isAdmin: boolean }) {
  const [language, setLanguage] = useState(initialLanguage); const [open, setOpen] = useState<string>(); const [chat, setChat] = useState(false); const zh = language === "zh";
  const questions = products.flatMap((product) => [
    { id: `${product.id}-moq`, question: zh ? `${product.nameZh} 的起订量和交期是多少？` : `What are the MOQ and lead time for ${product.nameEn}?`, answer: zh ? `起订量为 ${product.moq} 件，标准交期为 ${product.leadTime}。最终交期以规格、包装和订单数量确认结果为准。` : `MOQ is ${product.moq} units and standard lead time is ${product.leadTime}. Final timing depends on specifications, packaging and order volume.` },
    { id: `${product.id}-specs`, question: zh ? `${product.nameZh} 有哪些主要参数？` : `What are the key specifications of ${product.nameEn}?`, answer: Object.entries(product.specs).map(([key, value]) => `${key}: ${value}`).join(" · ") },
  ]);
  return <main className="min-h-screen bg-[#f6f8f6]"><SolutionHeader language={language} onLanguageChange={setLanguage} isAdmin={isAdmin} />
    <section className="border-b border-[#dce5e0] bg-[#073c2c] py-16 text-white sm:py-20"><div className="shell grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><span className="flex items-center gap-2 text-xs font-black uppercase text-[#d8f06d]"><Sparkles size={15} />{zh ? "全天候产品问答" : "24/7 product answers"}</span><h1 className="display mt-5 max-w-3xl text-5xl leading-[1.03] sm:text-6xl">{zh ? "先看常见问题，再与 AI 产品顾问深入沟通。" : "Start with proven answers, then go deeper with an AI product specialist."}</h1></div><p className="text-sm leading-7 text-white/65">{zh ? "所有答案均基于当前产品数据库。涉及最终价格、库存和合同条款时，将由出口顾问确认。" : "Answers are grounded in the current product database. Final pricing, stock and contract terms are confirmed by an export specialist."}</p></div></section>
    <div className="shell grid gap-10 py-14 lg:grid-cols-[.9fr_1.1fr]"><section><div className="mb-6 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[6px] bg-[#e2eee8] text-[#0b5d43]"><MessageCircleQuestion size={20} /></span><div><h2 className="font-bold">{zh ? "常见产品问题" : "Common product questions"}</h2><p className="mt-1 text-xs text-[#748079]">{zh ? `${questions.length} 个基于真实产品数据的回答` : `${questions.length} answers based on real product data`}</p></div></div><div className="space-y-2">{questions.map((item) => <div key={item.id} className="overflow-hidden rounded-[7px] border border-[#dae3de] bg-white"><button onClick={() => setOpen(open === item.id ? undefined : item.id)} className="flex w-full items-center justify-between gap-4 px-4 py-4 text-left text-sm font-bold"><span>{item.question}</span><ChevronDown className={`shrink-0 transition ${open === item.id ? "rotate-180" : ""}`} size={17} /></button>{open === item.id && <p className="border-t border-[#e6ebe8] bg-[#fafcfa] px-4 py-4 text-sm leading-6 text-[#5f6d66]">{item.answer}</p>}</div>)}</div><div className="mt-6 rounded-[7px] bg-[#eaf2ee] p-5"><ShieldCheck className="text-[#0b5d43]" size={20} /><p className="mt-3 text-xs leading-6 text-[#53615a]">{zh ? "没有找到答案？AI 会读取相同的产品知识库，并保持多轮对话上下文。" : "Could not find the answer? AI reads the same product knowledge and keeps multi-turn context."}</p><Button className="mt-4" onClick={() => setChat(true)}>{zh ? "进入 AI 对话" : "Start AI conversation"}</Button></div></section>
      <div>{chat ? <InlineAiChat key={language} language={language} /> : <div className="grid min-h-[580px] place-items-center rounded-[8px] border border-dashed border-[#bfcfc7] bg-[#eef4f1] p-8 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-[7px] bg-white text-[#0b5d43] shadow-sm"><Sparkles size={25} /></span><h2 className="display mt-5 text-3xl">{zh ? "准备好继续提问了吗？" : "Ready to continue the conversation?"}</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-[#68756f]">{zh ? "浏览左侧常见问题后，启动 DeepSeek 产品顾问进行个性化咨询。" : "Review common questions, then start the DeepSeek specialist for a tailored consultation."}</p><Button className="mt-6" size="lg" onClick={() => setChat(true)}>{zh ? "启动 AI 产品顾问" : "Launch AI specialist"}</Button></div></div>}</div></div>
  </main>;
}
